# Generated by Django 2.2.1 on 2019-05-14 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(choices=[('JAN', 'Janeiro'), ('FEV', 'Fevereiro'), ('MAR', 'Março'), ('ABR', 'Abril'), ('MAIO', 'Maio'), ('JUN', 'Junho'), ('JUL', 'Julho'), ('AGO', 'Agosto'), ('SET', 'Setembro'), ('OUT', 'Outubro'), ('NOV', 'Novembro'), ('DEZ', 'Dezembro')], default='JAN', max_length=3)),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=300)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=300)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens_album')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario.Album')),
            ],
        ),
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='titulo', max_length=100)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='diario.Album')),
            ],
        ),
    ]
